name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [clr, dpc]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Install platform deps for clr
        run: |
          sudo apt install libasound2-dev
      - name: Build
        run: cargo check --manifest-path ${{ matrix.project }}/Cargo.toml
      - name: Test
        run: cargo test --manifest-path ${{ matrix.project }}/Cargo.toml
