name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [clr, cool-bear-async-stuff, dpc, night-crab]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install platform deps for clr
        run: sudo apt install libasound2-dev
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: ${{ matrix.project }}
      - name: Format
        run: cargo fmt --all --manifest-path ${{ matrix.project }}/Cargo.toml
      - name: Build
        run: cargo check --manifest-path ${{ matrix.project }}/Cargo.toml
      - name: Test
        run: cargo test --manifest-path ${{ matrix.project }}/Cargo.toml
